export const APPLICATION_STEPS = [
  "General Information",
  "Your Background",
  "Short Answers",
  "MLH Agreements",
];

export const DEFAULT_FORM_VALUES = {
  firstName: "",
  lastName: "",
  age: undefined,
  pronouns: {
    value: "",
    customValue: "",
  },
  email: "",
  github: "",
  linkedin: "",
  personalWebsite: "",
  school: "",
  major: "",
  graduationYear: undefined,
  levelOfStudy: "",
  technicalInterests: "",
  hackathonsAttended: "",
  gender: "",
  race: "",
  country: "",
  shortAnswer1: "",
  shortAnswer2: "",
  mlhCheckbox1: false,
  mlhCheckbox2: false,
  mlhCheckbox3: false,
  resumeUrl: "",
  shareResume: false,
};
